services:
    phlexible_access_control.doctrine.access_manager:
        class: Phlexible\Component\AccessControl\Doctrine\AccessManager
        arguments:
            - "@phlexible_access_control.permission_registry"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "%phlexible_user.user.class%"
            - "%phlexible_user.group.class%"
